### ISSUE TITLE
本地跑不起 来缺少config 文件

### ISSUE THREAD

**Issue by mimimile** [QiShaoXuan/css_tricks#57]
```
// initComment.js
const CONFIG = require("../../../../config");

// config.js
const CONFIG = require("../../config");

// i18n/index.js
import { defaultLang, config } from "./config";
```

**Comment by itxcc** [comment]
本地根目录创建了 config.js，可以运行起来，但没内容

请问里面是需要什么配置内容？

**Comment by yukinotech** [comment]
同上，根据md里的步骤操作，执行`npm run docs:dev`这一步提示报错
```
> npx vuepress dev docs

wait Extracting site metadata...
Error: Cannot find module '../../config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```

**Comment by QiShaoXuan** [comment]
这个 config 里放的是我私人东西，所以没有提交。
可以在根目录下创建 `config.js`，内容为
```
module.exports = {
  gitalk: {},
  ga: ""
};
```

**Comment by QiShaoXuan** [comment]
也可以在 `docs/.vuepress/config.js` 中删除插件配置中的`require("./plugins/comment/index")`和 `["@vuepress/google-analytics",{ga: CONFIG.ga}],`
